import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          dark: "var(--color-primary-dark)",
          light: "var(--color-primary-light)",
          muted: "var(--color-primary-muted)",
          subtle: "var(--color-primary-subtle)",
          50: "#f0f5f7",
          100: "#dbe8ec",
          200: "#bad3dc",
          300: "#8eb6c4",
          400: "#5c93a8",
          500: "#3f778c",
          600: "#326072",
          700: "#264653", // Charcoal Blue Core
          800: "#213a45",
          900: "#1d323b",
          950: "#111f26",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          dark: "var(--color-secondary-dark)",
          light: "var(--color-secondary-light)",
          subtle: "var(--color-secondary-subtle)",
          50: "#f0faf8",
          100: "#d8f2ee",
          200: "#b5e5de",
          300: "#86d2c8",
          400: "#50b7ab",
          500: "#2A9D8F", // Verdigris Core
          600: "#248378",
          700: "#216a62",
          800: "#1e544f",
          900: "#1c4743",
        },
        highlight: {
          DEFAULT: "var(--color-highlight)",
          dark: "var(--color-highlight-dark)",
          light: "var(--color-highlight-light)",
          subtle: "var(--color-highlight-subtle)",
          50: "#fdfbf4",
          100: "#fbf6e3",
          200: "#f6ecc6",
          300: "#f0dda0",
          400: "#e9c46a", // Jasmine Core
          500: "#dfb44a",
          600: "#c49337",
          700: "#9d6e2c",
          800: "#805829",
          900: "#6d4926",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          dark: "var(--color-accent-dark)",
          light: "var(--color-accent-light)",
          subtle: "var(--color-accent-subtle)",
          50: "#fef8f4",
          100: "#fdefdf",
          200: "#fbdabf",
          300: "#f8bf95",
          400: "#F4A261", // Sandy Brown Core
          500: "#ee823b",
          600: "#df6627",
          700: "#b94d1f",
          800: "#933f20",
          900: "#77361d",
        },
        "strong-accent": {
          DEFAULT: "var(--color-strong-accent)",
          dark: "var(--color-strong-accent-dark)",
          light: "var(--color-strong-accent-light)",
          subtle: "var(--color-strong-accent-subtle)",
          50: "#fdf4f2",
          100: "#fce6e1",
          200: "#fad1c7",
          300: "#f5b0a0",
          400: "#ee8770",
          500: "#E76F51", // Burnt Peach Core
          600: "#d45030",
          700: "#b23e23",
          800: "#923620",
          900: "#7a3120",
        },
        background: {
          DEFAULT: "var(--color-background)",
          subtle: "var(--color-background-subtle)",
          muted: "var(--color-background-muted)",
        },
        text: {
          DEFAULT: "var(--color-text)",
          primary: "var(--color-text)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          inverse: "var(--color-text-inverse)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          elevated: "var(--color-surface-elevated)",
          muted: "var(--color-surface-muted)",
          border: "var(--color-border)",
          "border-subtle": "var(--color-border-subtle)",
          "border-strong": "var(--color-border-strong)",
        },
        feedback: {
          success: "var(--color-success)",
          "success-subtle": "var(--color-success-subtle)",
          warning: "var(--color-warning)",
          "warning-subtle": "var(--color-warning-subtle)",
          error: "var(--color-error)",
          "error-subtle": "var(--color-error-subtle)",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "Instrument Serif", "Georgia", "serif"],
        sans: ["var(--font-sans)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-sans)", "Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "hero-name": ["var(--font-size-hero-name)", { lineHeight: "1.02", letterSpacing: "-0.03em" }],
        display: ["var(--font-size-display)", { lineHeight: "var(--line-height-tight)", letterSpacing: "var(--letter-spacing-tight)" }],
        h1: ["var(--font-size-h1)", { lineHeight: "var(--line-height-tight)", letterSpacing: "var(--letter-spacing-tight)" }],
        h2: ["var(--font-size-h2)", { lineHeight: "var(--line-height-snug)", letterSpacing: "var(--letter-spacing-tight)" }],
        h3: ["var(--font-size-h3)", { lineHeight: "var(--line-height-snug)", letterSpacing: "var(--letter-spacing-normal)" }],
        h4: ["var(--font-size-h4)", { lineHeight: "var(--line-height-snug)", letterSpacing: "var(--letter-spacing-normal)" }],
        "body-large": ["var(--font-size-body-large)", { lineHeight: "var(--line-height-normal)" }],
        body: ["var(--font-size-body)", { lineHeight: "var(--line-height-normal)" }],
        "body-small": ["var(--font-size-body-small)", { lineHeight: "var(--line-height-normal)" }],
        caption: ["var(--font-size-caption)", { lineHeight: "var(--line-height-normal)" }],
        eyebrow: ["var(--font-size-eyebrow)", { lineHeight: "1", letterSpacing: "var(--letter-spacing-eyebrow)" }],
        metadata: ["var(--font-size-metadata)", { lineHeight: "1.4" }],
      },
      boxShadow: {
        hairline: "var(--shadow-hairline)",
        subtle: "var(--shadow-subtle)",
        card: "var(--shadow-card)",
        elevated: "var(--shadow-elevated)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      maxWidth: {
        reading: "var(--container-reading)",
        standard: "var(--container-standard)",
        editorial: "var(--container-editorial)",
        "editorial-full": "var(--container-full)",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "1.5rem",
          lg: "2rem",
          xl: "2.5rem",
          "2xl": "3rem",
        },
        screens: {
          sm: "640px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1440px",
        },
      },
      transitionTimingFunction: {
        editorial: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
